------------------------------------------------------------------------------------
--
-- Filename: xeno_schema_2.sql
--
-- Since: Tue Dec 26 09:11:53 CET 2017
--
-- This file was generated by Kripton Annotation Processor v. 3.1.0
--
------------------------------------------------------------------------------------

CREATE TABLE hello (id INTEGER PRIMARY KEY AUTOINCREMENT, area INTEGER, code TEXT UNIQUE NOT NULL, calling_code TEXT NOT NULL, region TEXT, name TEXT NOT NULL, translated_name BLOB);
CREATE TABLE prefix_config (id INTEGER PRIMARY KEY AUTOINCREMENT, default_country TEXT, dual_billing_prefix TEXT, enabled INTEGER, dialog_timeout INTEGER, skip_message INTEGER);
CREATE TABLE phone_number (id INTEGER PRIMARY KEY AUTOINCREMENT, action TEXT, number TEXT, country_code TEXT, contact_name TEXT, contact_id TEXT);
